//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Alen.Toma")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright (c) 2016 Alen Toma")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("FastDeepCloner is very fast portable library, This is a C# cross platform library" +
    " that is used to deep clone objects, whether they are serializable or not. It in" +
    "tends to be much faster than the normal binary serialization method of deep clon" +
    "ing objects.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.2.5")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.2.5")]
[assembly: System.Reflection.AssemblyProductAttribute("FastDeepCloner")]
[assembly: System.Reflection.AssemblyTitleAttribute("FastDeepCloner")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.2.5")]

// Generated by the MSBuild WriteCodeFragment class.

